### ISSUE TITLE
Interactive Mode or Not

### ISSUE THREAD

**Issue by jiefeng-xu** [k-takata/ptycheck#1]
This is a feature request. Is it possible to determine if the go code is running in interactive mode or not? So that we can decide if we need to use the options / flag or interactive with end user for options.

**Comment by k-takata** [comment]
I'm not sure what your request is.
In case of `python` command, it will go to interactive mode if no arguments are given and stdios are not redirected or `-i` is given as an argument.
Ptycheck just checks if a program is executed inside Command Prompt or mintty. Interactive mode or not is a different matter.

**Comment by jiefeng-xu** [comment]
Thanks @k-takata . Here is an example for what I am looking for.

I have a program which provides the command. For example I have "abc delete" to delete the instance of myself. The thing is, my program has already be called in many scripts by others by calling "abc delete". One day I realize that it might be good to prompt to confirm the deletion before it is really deleted, so by default, my program turns to prompt confirm. If users types "abc delete", it will prompt to ask "do you really want to delete abc [y/N]?". But that will break all those scripts developed by others, since they want to directly call "abc delete" in their script to delete. On the other side, I do add a flag into my program. If user calls "abc delete -f" or "abc delete --force", it will be deleted silently.

The solution I am looking for is, is there a way to determine if my program is called in others' script? or if it is typed in the command. I want to **implement logic in my abc program code** that if it is typed in command line, it will still prompt confirmation, and if it is called in others' script, I want to delete abc silently. With that change, others' scripts don't need to change and function is not impacted.

**Comment by k-takata** [comment]
I understand, but I don't think there is a way to detect that without changing the caller scripts.

**Comment by jiefeng-xu** [comment]
Thank you @k-takata , I am going to close this issue.
